### ISSUE TITLE
set timestamp format for set downtime

### ISSUE THREAD

**Issue by brandoconnor** [brandoconnor/nagios_commander#2]
Timestamp format appears to differ from version to version of Nagios. The following was found to work in v 3.3.1:

-NOW=$(date +"%m-%d-%Y %H:%M:%S")

The next string was reported to work under 3.2.1:

+NOW=$(date +"%Y-%m-%dT%H:%M:%S")

I'll need to determine how string formatting correlates to version and modify the code accordingly. Alternatively, formatting could be flexibly specified by an argument if necessary.

**Comment by stephanwehr** [comment]
I've added a new variable to the globals section:
DATE_FORMAT='%m-%d-%Y %H:%M:%S'

and changed the following inside the script:
NOW_ADD_MINS=$(date +"$DATE_FORMAT" -d "+$MINUTES minute")
NOW=$(date +"$DATE_FORMAT")
NOW=$(date +"$DATE_FORMAT")

Nagios Version 3.0.6 on SLES 11 SP4

**Comment by brandoconnor** [comment]
I don't have the bandwidth or interest to maintain this repo any further as I haven't used Nagios in ages (for the best). Closing this issue down for housekeeping.
